package main

import (
	"encoding/json"
	"fmt"
)

type AutoGenerated struct {
	Nsqd []struct {
		Priority  int           `json:"priority"`
		Snapshot  string        `json:"snapshot"`
		Hostgroup string        `json:"hostgroup"`
		DependsOn []interface{} `json:"depends_on"`
		Skipped   bool          `json:"skipped,omitempty"`
	} `json:"nsqd"`
	// Other struct fields are omitted for brevity
}

type AutoGeneratedNew struct {
	Data []struct {
		PseJobName   string `json:"pse job name"`
		NameResource string `json:"name resource"`
		Problem      string `json:"problem"`
		Notes        string `json:"notes"`
	} `json:"data"`
}

func main() {
	// Contoh data struct AutoGenerated
	data := AutoGenerated{
		Nsqd: []struct {
			Priority  int           `json:"priority"`
			Snapshot  string        `json:"snapshot"`
			Hostgroup string        `json:"hostgroup"`
			DependsOn []interface{} `json:"depends_on"`
			Skipped   bool          `json:"skipped,omitempty"`
		}{
			{
				Priority:  1,
				Snapshot:  "snapshot1",
				Hostgroup: "hostgroup1",
				DependsOn: []interface{}{"dep1", "dep2"},
				Skipped:   true,
			},
			{
				Priority:  2,
				Snapshot:  "snapshot2",
				Hostgroup: "hostgroup2",
				DependsOn: []interface{}{"dep3", "dep4"},
				Skipped:   false,
			},
		},
	}

	// Konversi struct AutoGenerated ke struct AutoGeneratedNew
	var newData AutoGeneratedNew
	newData.Data = make([]struct {
		PseJobName   string `json:"pse job name"`
		NameResource string `json:"name resource"`
		Problem      string `json:"problem"`
		Notes        string `json:"notes"`
	}, 0)
	for _, nsqd := range data.Nsqd {
		if nsqd.Skipped {
			newData.Data = append(newData.Data, struct {
				PseJobName   string `json:"pse job name"`
				NameResource string `json:"name resource"`
				Problem      string `json:"problem"`
				Notes        string `json:"notes"`
			}{
				PseJobName: "nsqd",
				NameResource: nsqd.Snapshot,
				Problem: "",
				Notes: "skipped",
				})
				}
				}

// Print struct AutoGeneratedNew ke json
jsonData, _ := json.Marshal(newData)
fmt.Println(string(jsonData))
}